### ISSUE TITLE
assets bug

### ISSUE THREAD

**Issue by palo2583** [PUGX/PUGXAutoCompleterBundle#49] opened 2018-02-17 18:59 UTC
hello, in version 1.4.1 when i run bin/console assets:install, assets didn't install in to web/bundles
in 1.3.1 works fine. 

thanks.

**Comment by palo2583** [comment] 2018-02-17 19:13
i think, problem is here https://github.com/PUGX/PUGXAutoCompleterBundle/blob/v1.4.1/src/DependencyInjection/PUGXAutocompleterExtension.php
in filelocator path

**Comment by garak** [comment] 2018-02-23 14:42
I just tried in a project with Symfony 3.4 and I got assets installed correctly

**Comment by mwiercioch** [comment] 2018-02-28 21:52
Problem still exists. My project is built with symfony 3.4, assets are not being install correctly(1.4)

**Comment by garak** [comment] 2018-03-01 07:45
Please provide a way to reproduce problem

**Comment by palo2583** [comment] 2018-03-01 07:53
i wrote it in first post

**Comment by garak** [comment] 2018-03-01 08:36
Unfortunately, "it's not working for me" is not a way to reproduce problems

**Comment by palo2583** [comment] 2018-03-01 09:09
after composer require pubx/....

![snimka obrazovky 2018-03-01 o 10 02 52](https://user-images.githubusercontent.com/23255140/36836008-53e63b64-1d38-11e8-98b2-dc73f9bbaa35.png)
assets didn't install

i trying run bin/console assets:install 
![snimka obrazovky 2018-03-01 o 10 03 16](https://user-images.githubusercontent.com/23255140/36836050-7588e140-1d38-11e8-9a55-bfadce9b8d33.png)
assets did'nt install

in version 1.3.1 assets installed without problem

**Comment by garak** [comment] 2018-03-01 09:24
Try with version `^1.5@dev`

**Comment by Laurent5** [comment] 2018-04-16 18:25
Hi, I had the same bug.

`^1.5@dev` working for me, thanks !

**Comment by Puerco-Potter** [comment] 2018-08-25 14:15
Hi, I am experiencing this on symfony 4, using the ^1.5@dev version with flex
![2018-08-25 11_13_36-git cmd](https://user-images.githubusercontent.com/28161570/44619141-1e13c280-a858-11e8-88bb-80f2d053c8f7.png)

**Comment by garak** [comment] 2018-08-25 14:36
@Puerco-Potter sorry, no support for systems without symlinks (like Windows)

**Comment by Rubc** [comment] 2019-01-04 13:23
When using the latest version, the assets are still not installed, I suggest to move the resources folder to the src. Is this possible?

**Comment by snoop168** [comment] 2019-05-19 18:24
Not sure if this was supposed to be fixed or not.. it seems as though there is a symlink in src but for some reason when I installed this library by using composer it did not create a symlink on my machine, just a plain file....

**Comment by garak** [comment] 2019-05-19 18:47
Unfortunately, it's not fixed at the moment.
I have a project where the same deploy process is creating the symlink in one environment and **not** creating the same symlink in a different environment.
I just don't know where the problem is

**Comment by snoop168** [comment] 2019-05-21 10:06
It worked for me on my development box but when I tried to deploy to a test server that’s when it didn’t. I can probably say the only difference for me would have been using “composer require” on the dev box and “composer install” on the test. Maybe there was a difference in the way composer handled the unpacking of the files? I don’t have time to test today but I’ll try to as soon as I can and report back.

**Comment by garak** [comment] 2019-05-21 13:24
@snoop168 I do "composer install" on both my environments, I'm afraid that's not the culprit

**Comment by garak** [comment] 2019-08-09 07:18
Fixed in ebb6876fcd5a1c1fa684fa3f539d32ee4726968f

**Closed by garak** 2019-08-09 07:18 UTC
